### ISSUE TITLE
about time format?

### ISSUE THREAD

**Issue by qssq** [alexbruno/hexo-generator-json-content#10]
2016-09-03T06:41:06.169Z

i i need 2016-9-03 
soruces date:2016-11-5 23:46:13 or 2016-11-5  but json generator is 2016-09-03T06:41:06.169Z

format
请问应该怎么做呀,我不想 正则出前面的。后面的不知道是啥 看不懂格式

**Comment by alexbruno** [comment]
Hello, sorry for late response!

Ok, maybe I will try to add format options, but the current format is a universal date and time format. Most program languages understand it.

If you need a specific format, you can do it by treating the data on your consumer application.

For example, in JavaScript you can do this:

```javascript
let dt = '2016-09-03T06:41:06.169Z',
    notime = dt.split('T')[0]
```

Or anything that give you the needed format.

**Comment by alexbruno** [comment]
Hello again!

New update was pushed and now this plugin support date formats using [moment](https://github.com/moment/moment/).

`README` simple documentation was updated too and can help you to understand how it works.

Get the latest version and enjoy!

👍

**Comment by qssq** [comment]
thank
