### ISSUE TITLE
can't generate "content.json" in ./public

### ISSUE THREAD

**Issue by coderSkyChen** [alexbruno/hexo-generator-json-content#14]
I have installed the "hexo-generator-json-content" with:
npm i -S hexo-generator-json-content

but, after "hexo g" there is no "content.json" generated in the root/public/

waitting for your attention :-)

**Comment by coderSkyChen** [comment]
This issue has been solved!
by: install the 2.* version not the latest version.....

**Comment by alexbruno** [comment]
Hello!
Please tell me more about it.
Version 3 don't works? What node version you are using?

**Comment by coderSkyChen** [comment]
Hi! @alexbruno 
Thanks for your contribution, now i have a pretty hexo theme:yillia ,with the content search ~
Here is my versions:
node : 4.5.0
npm : 4.0.3
hexo : 
hexo: 3.2.2
hexo-cli: 1.0.2
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.7.0
node: 4.5.0
v8: 4.5.103.37
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h

**Comment by alexbruno** [comment]
Ok.
Latest version of this plugin was coded with ES6, so it needs latest versions of Node.js to compile.

[https://nodejs.org/en/](https://nodejs.org/en/)
