### ISSUE TITLE
json-content for custom properties

### ISSUE THREAD

**Issue by ghost** [alexbruno/hexo-generator-json-content#22]
Do you know how to make SEARCH work for "custom properties"? For example, "author".

For example, I have in my .md files author: Mickey Mouse and in another .md file I have author: Donald Duck. So that when you search "Donald", then the search result for author Donald Duck appears.

I tried adding "author: true" to the json-content-generator list but that did not work.

**Comment by alexbruno** [comment]
Author added to the json.
