### ISSUE TITLE
Getting error : 'hexo' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by smartcookiemedia** [alexbruno/hexo-generator-json-content#23]
Hi there

I am having problems running Hexo on CLI.
After installing :
npm i -S hexo-generator-json-content

I get the error :
'hexo' is not recognized as an internal or external command.

I have node.js version:

v8.9.4

Any assistance wold be helpful.

Thanks

**Comment by alexbruno** [comment]
Hello, sorry for very late response!

Are you still running into this problem?

**Comment by alexbruno** [comment]
Closing because it's very possible this was a project/setup error.
