### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by nailerHeum** [alexbruno/hexo-generator-json-content#25]
/content.json could not be found.

I just installed on my theme's root by npm,

But I got that error and searching didn't work.

So I want to try to make a file, but where should I took the file??
I'll try making the file under the theme's root, or under the source.
please let me know how to solve this problem

**Comment by MarceloBarrera** [comment]
If you are using IIS as web server you need to tell the server that is able to process it::
<configuration>
    <system.webServer>
        <staticContent>
            <mimeMap fileExtension=".json" mimeType="application/json" />
     </staticContent>
    </system.webServer>
</configuration>

**Comment by alexbruno** [comment]
Closing because it's very possible this was a project/setup error.
