### ISSUE TITLE
Custom file name for content.json 

### ISSUE THREAD

**Issue by blurHY** [alexbruno/hexo-generator-json-content#26]
Hexo's `content.json` and ZeroNet's `content.json` conflict

**Comment by alexbruno** [comment]
Hello, thanks for contributing!
**hexo-generator-json-content** is older than ZeroNet. In fact, I have never heard about ZeroNet until now.
But, I will work on this issue ASAP.

**Comment by alexbruno** [comment]
Ok, solved on release v4.0.0.
