### ISSUE TITLE
keywords language

### ISSUE THREAD

**Issue by Buzut** [alexbruno/hexo-generator-json-content#28]
Thanks for your 4.1.1 fix!
I must have missed something because I keep getting this error:

```
Error: Language must be one of [danish,dutch,english,french,galician,german,italian,polish,portuguese,russian,spanish,swedish]
```

Where, how should I set the language in the yml?

I tried in the main `jsonContent`, directly in `jsonContent.posts` and also as a property of `keywords` in both of them…

**Comment by Buzut** [comment]
Ohhh, found it by checking the code!
in the main object it's not `keywords: true` but `keywords: LANG`.

The README wasn't clear about it.

**Comment by alexbruno** [comment]
Thanks @Buzut !
I merged your PR and will release a new patch.
