### ISSUE TITLE
page.description and post.description

### ISSUE THREAD

**Issue by itsEspen** [alexbruno/hexo-generator-json-content#30]
Can these fields be added to the index?

Insert the following on line 34 in utils.js:

    case 'description':
      obj.description = minify(ref.description);
      break

**Comment by alexbruno** [comment]
Hello, sorry for late response!
Thanks for contributing, I will add this ASAP.

**Comment by alexbruno** [comment]
Ok, released at [v4.2.1](https://github.com/alexbruno/hexo-generator-json-content/releases/tag/v4.2.1)
