### ISSUE TITLE
I'd like to know the contents of the categories and the tags.

### ISSUE THREAD

**Issue by KaiOrange** [alexbruno/hexo-generator-json-content#33]
I'd like to know the contents of the categories and the tags. Now I have to go through the fields in posts. Can you just generate the values inside？

**Comment by alexbruno** [comment]
Hello, thanks for this idea, and sorry for late response!
I will do it ASAP.

**Comment by alexbruno** [comment]
Ok, released at [v4.2.1](https://github.com/alexbruno/hexo-generator-json-content/releases/tag/v4.2.1)
