### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by noraj** [alexbruno/hexo-generator-json-content#34]
Could you provide a changelog either in CHANGELOG.md or https://github.com/alexbruno/hexo-generator-json-content/releases

because the following is a little light and does not say in which version the change are introduced.

![image](https://user-images.githubusercontent.com/16578570/68064749-c906f280-fd1f-11e9-9403-a54a86293c06.png)

**Comment by noraj** [comment]
bump

**Comment by alexbruno** [comment]
Hello and sorry for so late response!
I will do it ASAP.

**Comment by alexbruno** [comment]
Ok, I just wrote some basic info about main changes on latest releases.
I will try to maintain releases infos updated.

**Comment by noraj** [comment]
Thx I was waiting to update :)
