### ISSUE TITLE
db.json instead of content.json

### ISSUE THREAD

**Issue by veramartins** [alexbruno/hexo-generator-json-content#7]
Everything works fine, except it generates a db.json file instead of content.json. I have to manually change the file name after each hexo generate.

**Comment by alexbruno** [comment]
Thanks for report and sorry for late response!
This issue will be fixed soon.

**Comment by alexbruno** [comment]
Sorry, I just ran a simple test here. It's all right and `content.json` was generated normally.

Please **don't reaname** your `db.json` file! It is generated by Hexo itself and is an important framework file.

If your `content.json` wasn't generated, something is working bad.

Try this:

If you are running `hexo server` to develop or test your site, the `content.json` file will not be generated physically in the file system, but only virtually.

Just access your site url and add `content.json` to access the generated content. Like: **http://localhost:4000/content.json**

When you run `hexo generate` command to build your static site, the `content.json` file will be generated physically in the file system in your public folder root.

**Comment by veramartins** [comment]
You are right, of course. I was using `hexo server` to develop locally and the search plugin couldn't find content.json. All I had to do was `hexo generate`. Thanks.
