### ISSUE TITLE
eroor  symbols error

### ISSUE THREAD

**Issue by qssq** [alexbruno/hexo-generator-json-content#9]
Hello, you can fix on the content of the special characters of the problem? JSON failed to normal output, such as the URL inside the JSON is wrong, because the article which contains a number of special symbols, http://qssq666.cn/content.json http://qssq666.cn/recent.json

**Comment by alexbruno** [comment]
Hello, sorry for late response! Is it working?
I saw your json contents and there are a lot of code inside, including JavaScript.
This plugin was not designed to embed code. Only content.
